/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    'Landing': RouteRecordInfo<
      'Landing',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/docs': RouteRecordInfo<
      '/docs',
      '/docs',
      Record<never, never>,
      Record<never, never>,
      | 'Accordion'
      | 'Avatar'
      | 'Breadcrumbs'
      | 'Button'
      | 'Buttons'
      | 'Checkbox'
      | 'Components'
      | 'Config'
      | 'Data'
      | 'Divider'
      | 'Documentations'
      | 'Form'
      | 'Group'
      | 'Hooks'
      | 'Icon'
      | 'IconButton'
      | 'Input'
      | 'ListBox'
      | 'Message'
      | 'Navigation'
      | 'Pagination'
      | 'Progress'
      | 'Radio'
      | 'ScrollArea'
      | 'Select'
      | 'SelectButton'
      | 'Skeleton'
      | 'Switch'
      | 'Table'
      | 'Tabs'
      | 'Tag'
      | 'Textarea'
      | 'useArrayModel'
      | 'useClickOutside'
      | 'useClipboard'
      | 'useColorScheme'
      | 'useFloating'
      | 'useGlobalEvent'
      | 'useKeyboardNavigation'
      | 'useTypeahead'
    >,
    'Documentations': RouteRecordInfo<
      'Documentations',
      '/docs/documentation',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Config': RouteRecordInfo<
      'Config',
      '/docs/documentation/config',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Hooks': RouteRecordInfo<
      'Hooks',
      '/docs/hooks',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'useArrayModel': RouteRecordInfo<
      'useArrayModel',
      '/docs/hooks/use-array-model',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'useClickOutside': RouteRecordInfo<
      'useClickOutside',
      '/docs/hooks/use-click-outside',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'useClipboard': RouteRecordInfo<
      'useClipboard',
      '/docs/hooks/use-clipboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'useColorScheme': RouteRecordInfo<
      'useColorScheme',
      '/docs/hooks/use-color-scheme',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'useFloating': RouteRecordInfo<
      'useFloating',
      '/docs/hooks/use-floating',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'useGlobalEvent': RouteRecordInfo<
      'useGlobalEvent',
      '/docs/hooks/use-global-event',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'useKeyboardNavigation': RouteRecordInfo<
      'useKeyboardNavigation',
      '/docs/hooks/use-keyboard-navigation',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'useTypeahead': RouteRecordInfo<
      'useTypeahead',
      '/docs/hooks/use-typeahead',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Components': RouteRecordInfo<
      'Components',
      '/docs/ui-kit',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Buttons': RouteRecordInfo<
      'Buttons',
      '/docs/ui-kit/buttons',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Button': RouteRecordInfo<
      'Button',
      '/docs/ui-kit/buttons/button',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'IconButton': RouteRecordInfo<
      'IconButton',
      '/docs/ui-kit/buttons/icon-button',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Data': RouteRecordInfo<
      'Data',
      '/docs/ui-kit/data',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Accordion': RouteRecordInfo<
      'Accordion',
      '/docs/ui-kit/data/accordion',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Avatar': RouteRecordInfo<
      'Avatar',
      '/docs/ui-kit/data/avatar',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Divider': RouteRecordInfo<
      'Divider',
      '/docs/ui-kit/data/divider',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Icon': RouteRecordInfo<
      'Icon',
      '/docs/ui-kit/data/icon',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Message': RouteRecordInfo<
      'Message',
      '/docs/ui-kit/data/message',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Progress': RouteRecordInfo<
      'Progress',
      '/docs/ui-kit/data/progress',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'ScrollArea': RouteRecordInfo<
      'ScrollArea',
      '/docs/ui-kit/data/scroll-area',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Skeleton': RouteRecordInfo<
      'Skeleton',
      '/docs/ui-kit/data/skeleton',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Table': RouteRecordInfo<
      'Table',
      '/docs/ui-kit/data/table',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Tag': RouteRecordInfo<
      'Tag',
      '/docs/ui-kit/data/tag',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Form': RouteRecordInfo<
      'Form',
      '/docs/ui-kit/form',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Checkbox': RouteRecordInfo<
      'Checkbox',
      '/docs/ui-kit/form/checkbox',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Group': RouteRecordInfo<
      'Group',
      '/docs/ui-kit/form/group',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Input': RouteRecordInfo<
      'Input',
      '/docs/ui-kit/form/input',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'ListBox': RouteRecordInfo<
      'ListBox',
      '/docs/ui-kit/form/listbox',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Radio': RouteRecordInfo<
      'Radio',
      '/docs/ui-kit/form/radio',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Select': RouteRecordInfo<
      'Select',
      '/docs/ui-kit/form/select',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'SelectButton': RouteRecordInfo<
      'SelectButton',
      '/docs/ui-kit/form/select-button',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Switch': RouteRecordInfo<
      'Switch',
      '/docs/ui-kit/form/switch',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Textarea': RouteRecordInfo<
      'Textarea',
      '/docs/ui-kit/form/textarea',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Navigation': RouteRecordInfo<
      'Navigation',
      '/docs/ui-kit/navigation',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Breadcrumbs': RouteRecordInfo<
      'Breadcrumbs',
      '/docs/ui-kit/navigation/breadcrumbs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Pagination': RouteRecordInfo<
      'Pagination',
      '/docs/ui-kit/navigation/pagination',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Tabs': RouteRecordInfo<
      'Tabs',
      '/docs/ui-kit/navigation/tabs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Layout': RouteRecordInfo<
      'Layout',
      '/layout',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Base layout': RouteRecordInfo<
      'Base layout',
      '/layout/base',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | 'Landing'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/docs.vue': {
      routes:
        | '/docs'
        | 'Accordion'
        | 'Avatar'
        | 'Breadcrumbs'
        | 'Button'
        | 'Buttons'
        | 'Checkbox'
        | 'Components'
        | 'Config'
        | 'Data'
        | 'Divider'
        | 'Documentations'
        | 'Form'
        | 'Group'
        | 'Hooks'
        | 'Icon'
        | 'IconButton'
        | 'Input'
        | 'ListBox'
        | 'Message'
        | 'Navigation'
        | 'Pagination'
        | 'Progress'
        | 'Radio'
        | 'ScrollArea'
        | 'Select'
        | 'SelectButton'
        | 'Skeleton'
        | 'Switch'
        | 'Table'
        | 'Tabs'
        | 'Tag'
        | 'Textarea'
        | 'useArrayModel'
        | 'useClickOutside'
        | 'useClipboard'
        | 'useColorScheme'
        | 'useFloating'
        | 'useGlobalEvent'
        | 'useKeyboardNavigation'
        | 'useTypeahead'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/docs/documentation/index.vue': {
      routes:
        | 'Documentations'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/docs/documentation/config/index.vue': {
      routes:
        | 'Config'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/docs/hooks/index.vue': {
      routes:
        | 'Hooks'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/docs/hooks/use-array-model/index.vue': {
      routes:
        | 'useArrayModel'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/docs/hooks/use-click-outside/index.vue': {
      routes:
        | 'useClickOutside'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/docs/hooks/use-clipboard/index.vue': {
      routes:
        | 'useClipboard'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/docs/hooks/use-color-scheme/index.vue': {
      routes:
        | 'useColorScheme'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/docs/hooks/use-floating/index.vue': {
      routes:
        | 'useFloating'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/docs/hooks/use-global-event/index.vue': {
      routes:
        | 'useGlobalEvent'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/docs/hooks/use-keyboard-navigation/index.vue': {
      routes:
        | 'useKeyboardNavigation'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/docs/hooks/use-typeahead/index.vue': {
      routes:
        | 'useTypeahead'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/docs/ui-kit/index.vue': {
      routes:
        | 'Components'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/docs/ui-kit/buttons/index.vue': {
      routes:
        | 'Buttons'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/docs/ui-kit/buttons/button/index.vue': {
      routes:
        | 'Button'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/docs/ui-kit/buttons/icon-button/index.vue': {
      routes:
        | 'IconButton'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/docs/ui-kit/data/index.vue': {
      routes:
        | 'Data'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/docs/ui-kit/data/accordion/index.vue': {
      routes:
        | 'Accordion'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/docs/ui-kit/data/avatar/index.vue': {
      routes:
        | 'Avatar'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/docs/ui-kit/data/divider/index.vue': {
      routes:
        | 'Divider'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/docs/ui-kit/data/icon/index.vue': {
      routes:
        | 'Icon'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/docs/ui-kit/data/message/index.vue': {
      routes:
        | 'Message'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/docs/ui-kit/data/progress/index.vue': {
      routes:
        | 'Progress'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/docs/ui-kit/data/scroll-area/index.vue': {
      routes:
        | 'ScrollArea'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/docs/ui-kit/data/skeleton/index.vue': {
      routes:
        | 'Skeleton'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/docs/ui-kit/data/table/index.vue': {
      routes:
        | 'Table'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/docs/ui-kit/data/tag/index.vue': {
      routes:
        | 'Tag'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/docs/ui-kit/form/index.vue': {
      routes:
        | 'Form'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/docs/ui-kit/form/checkbox/index.vue': {
      routes:
        | 'Checkbox'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/docs/ui-kit/form/group/index.vue': {
      routes:
        | 'Group'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/docs/ui-kit/form/input/index.vue': {
      routes:
        | 'Input'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/docs/ui-kit/form/listbox/index.vue': {
      routes:
        | 'ListBox'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/docs/ui-kit/form/radio/index.vue': {
      routes:
        | 'Radio'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/docs/ui-kit/form/select/index.vue': {
      routes:
        | 'Select'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/docs/ui-kit/form/select-button/index.vue': {
      routes:
        | 'SelectButton'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/docs/ui-kit/form/switch/index.vue': {
      routes:
        | 'Switch'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/docs/ui-kit/form/textarea/index.vue': {
      routes:
        | 'Textarea'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/docs/ui-kit/navigation/index.vue': {
      routes:
        | 'Navigation'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/docs/ui-kit/navigation/breadcrumbs/index.vue': {
      routes:
        | 'Breadcrumbs'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/docs/ui-kit/navigation/pagination/index.vue': {
      routes:
        | 'Pagination'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/docs/ui-kit/navigation/tabs/index.vue': {
      routes:
        | 'Tabs'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/layout/index.vue': {
      routes:
        | 'Layout'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/layout/base/index.vue': {
      routes:
        | 'Base layout'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
