import type { Component } from 'vue'
import { createUiKit } from '@dotdev/ui-kit'

/* Icon map generated by the @dotdev/icons Vite plugin */
const icons: Record<string, Component> = {}

export const uiKit = createUiKit({
  base: { namespace: 'd', icons },
  configs: [
    {
      namespace: 'landing',
      theme: {
        primitives: {/* …own brand ramp and scale… */},
        semantics: {/* …re-mapped tokens… */},
      },
    },
  ],
})
