import type { UiKitBoxCore } from './primitives.types.ts'

/**
 * Runtime-источник истины для плагина (фильтрация атрибутов по типам).
 * Должен покрывать все ключи UiKitBoxCore.
 */
export const boxCoreKeys = [
  'display',
  'hidden',
  'visible',
  'position',
  'inset',
  'top',
  'right',
  'bottom',
  'left',
  'float',
  'z',
  'direction',
  'wrap',
  'inline',
  'justify',
  'align',
  'content',
  'self',
  'order',
  'center',
  'gap',
  'grow',
  'shrink',
  'basis',
  'cols',
  'rows',
  'flow',
  'autoCols',
  'autoRows',
  'placeItems',
  'placeSelf',
  'placeContent',
  'w',
  'h',
  'minW',
  'minH',
  'maxW',
  'maxH',
  'size',
  'aspect',
  'p',
  'px',
  'py',
  'pt',
  'pr',
  'pb',
  'pl',
  'm',
  'mx',
  'my',
  'mt',
  'mr',
  'mb',
  'ml',
  'spaceX',
  'spaceY',
  'overflow',
  'overflowX',
  'overflowY',
  'overscroll',
  'bg',
  'border',
  'borderColor',
  'borderStyle',
  'rounded',
  'shadow',
  'ring',
  'outline',
  'opacity',
  'cursor',
  'select',
  'pointerEvents',
  'resize',
  'objectFit',
  'objectPosition',
  'transition',
  'animate',
  '$class',
] as const satisfies readonly (keyof UiKitBoxCore)[]

export const boxBreakpoints = ['sm', 'md', 'lg', 'xl', '2xl'] as const satisfies readonly string[]

export const boxVariants = ['hover', 'focus', 'focus-visible', 'focus-within', 'active', 'disabled'] as const satisfies readonly string[]

// Type-level проверка полноты: каждый ключ UiKitBoxCore должен присутствовать в boxCoreKeys
type MissingBoxKey = Exclude<keyof UiKitBoxCore, (typeof boxCoreKeys)[number]>
type AssertNever<T extends never> = T
export type _AssertBoxKeysComplete = AssertNever<MissingBoxKey>
